import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { register as registerGeneratePdf } from "./generate-pdf.js";
import { register as registerUploadFile } from "./upload-file.js";
import { register as registerGetDocument } from "./get-document.js";
import { register as registerDeleteDocument } from "./delete-document.js";
import { register as registerFlattenPdf } from "./flatten-pdf.js";
import { register as registerExtractFormData } from "./extract-form-data.js";
import { register as registerAddFormFields } from "./add-form-fields.js";
import { register as registerCompressPdf } from "./compress-pdf.js";
import { register as registerProtectPdf } from "./protect-pdf.js";
import { register as registerWatermarkPdf } from "./watermark-pdf.js";
import { register as registerDownloadFile } from "./download-file.js";
import { register as registerCreateEnvelope } from "./create-envelope.js";
import { register as registerSendEnvelope } from "./send-envelope.js";
import { register as registerGetEnvelope } from "./get-envelope.js";
import { register as registerVoidEnvelope } from "./void-envelope.js";
import { register as registerDeleteEnvelope } from "./delete-envelope.js";
import { register as registerCreateWebhook } from "./create-webhook.js";
import { register as registerGetWebhook } from "./get-webhook.js";
import { register as registerDeleteWebhook } from "./delete-webhook.js";

export function registerTools(server: McpServer): void {
  registerGeneratePdf(server);
  registerUploadFile(server);
  registerGetDocument(server);
  registerDeleteDocument(server);
  registerFlattenPdf(server);
  registerExtractFormData(server);
  registerAddFormFields(server);
  registerCompressPdf(server);
  registerProtectPdf(server);
  registerWatermarkPdf(server);
  registerDownloadFile(server);
  registerCreateEnvelope(server);
  registerSendEnvelope(server);
  registerGetEnvelope(server);
  registerVoidEnvelope(server);
  registerDeleteEnvelope(server);
  registerCreateWebhook(server);
  registerGetWebhook(server);
  registerDeleteWebhook(server);
}
